import { Post } from '../utils/types'; // Assuming you have a Post type defined

export const mockPosts: Post[] = [
  {
    id: 1,
    image: 'https://picsum.photos/seed/post1/800/400',
    imageUrl: 'https://picsum.photos/seed/post1/800/400',
    title: 'Celebrating Superchain Creativity(创造力): Announcing the Winners of "We ❤️The Art"',
    author: 'The Optimism(乐观) Collective',
    date: 'March(三月) 12',
    content: 'Amidst a whirlwind of creativity(创造力), We ❤️The Art has reached its conclusion, after seeing 7,000+ submissions seize(抓住) this OPportunity to share their art...',
    likes: 13,
    comments: 21,
    collectCount: 199
  },
  {
    id: 2,
    image: 'https://picsum.photos/seed/post2/400/300',
    imageUrl: 'https://picsum.photos/seed/post2/400/300',
    title: '[BONUS(奖金)] Crypto The Game Season 2 Recap, Reunion(团聚), and Confessions(忏悔)',
    author: 'Rehash: A Web3 Podcast',
    date: 'April 22',
    content: 'Crypto The Game founders(创始人) recap Season 2 and four finalists and players share their experiences and insights.',
    likes: 13,
    comments: 21,
    collectCount: 27
  },
  {
    id: 3,
    image: 'https://picsum.photos/seed/post3/400/300',
    imageUrl: 'https://picsum.photos/seed/post3/400/300',
    title: '"the updates" ENE',
    author: 'Xcelencia',
    date: 'April 20',
    content: 'In 2021, after successfully(成功) crowdfunding for the Infinxte album I launched(推出) an entry that I continuously(不断) updated with achievements, milestones, metrics, and more!',
    likes: 13,
    comments: 21,
    collectCount: 37
  },
  {
    id: 4,
    image: 'https://picsum.photos/seed/post4/400/300',
    imageUrl: 'https://picsum.photos/seed/post4/400/300',
    title: 'Bitcoin, Green Mining(矿井), and the Possibility for a More Sustainable(永续) Future',
    author: 'PYUSD',
    date: 'April 22',
    content: 'An opportunity to accelerate(加快) the clean energy transition(过渡) for Bitcoin mining(矿业)...',
    likes: 13,
    comments: 21,
    collectCount: 24
  },
  {
    id: 5,
    image: 'https://picsum.photos/seed/post5/400/300',
    imageUrl: 'https://picsum.photos/seed/post5/400/300',
    title: 'The Future of Decentralized Finance(去中心化金融)',
    author: 'DeFi Visionary',
    date: 'April 25',
    content: 'Exploring the potential of DeFi to revolutionize traditional financial systems and create new opportunities for global economic inclusion.',
    likes: 13,
    comments: 21,
    collectCount: 156
  },
  {
    id: 6,
    image: 'https://picsum.photos/seed/post6/400/300',
    imageUrl: 'https://picsum.photos/seed/post6/400/300',
    title: 'NFTs and the Art World: A New Renaissance(文艺复兴)?',
    author: 'Digital Art Enthusiast',
    date: 'April 28',
    content: 'Examining how NFTs are changing the landscape for artists and collectors, and what this means for the future of art creation and ownership.',
    likes: 13,
    comments: 21,
    collectCount: 89
  },
  {
    id: 7,
    image: 'https://picsum.photos/seed/post7/400/300',
    imageUrl: 'https://picsum.photos/seed/post7/400/300',
    title: 'The Rise of DAOs: Decentralized Governance in Action',
    author: 'Crypto Governance Expert',
    date: 'May 1',
    content: 'Analyzing the growth of Decentralized Autonomous Organizations and their potential to reshape organizational structures.',
    likes: 13,
    comments: 21,
    collectCount: 112
  },
  {
    id: 8,
    image: 'https://picsum.photos/seed/post8/400/300',
    imageUrl: 'https://picsum.photos/seed/post8/400/300',
    title: 'Layer 2 Solutions: Scaling Ethereum for Mass Adoption',
    author: 'Blockchain Scaling Researcher',
    date: 'May 3',
    content: 'Diving into various Layer 2 technologies and their role in making Ethereum more accessible and efficient for everyday use.',
    likes: 13,
    comments: 21,
    collectCount: 78
  },
  {
    id: 9,
    image: 'https://picsum.photos/seed/post9/400/300',
    imageUrl: 'https://picsum.photos/seed/post9/400/300',
    title: 'The Intersection of AI and Blockchain: Possibilities and Challenges',
    author: 'Tech Futurist',
    date: 'May 5',
    content: 'Exploring how artificial intelligence and blockchain technology can work together to create innovative solutions across industries.',
    likes: 13,
    comments: 21,
    collectCount: 203
  },
  {
    id: 10,
    image: 'https://picsum.photos/seed/post10/400/300',
    imageUrl: 'https://picsum.photos/seed/post10/400/300',
    title: 'Crypto Regulation: Navigating the Changing Landscape',
    author: 'Blockchain Legal Expert',
    date: 'May 8',
    content: 'An overview of recent regulatory developments in the cryptocurrency space and what they mean for investors and projects.',
    likes: 13,
    comments: 21,
    collectCount: 67
  },
  {
    id: 11,
    image: 'https://picsum.photos/seed/post11/400/300',
    imageUrl: 'https://picsum.photos/seed/post11/400/300',
    title: 'The Evolution of DeFi: From Yield Farming to Real-World Assets',
    author: 'DeFi Analyst',
    date: 'May 10',
    content: 'Tracing the development of DeFi protocols and their expansion into tokenizing traditional assets.',
    likes: 13,
    comments: 21,
    collectCount: 95
  },
  {
    id: 12,
    image: 'https://picsum.photos/seed/post12/400/300',
    imageUrl: 'https://picsum.photos/seed/post12/400/300',
    title: 'Web3 Gaming: The Next Frontier of Player Ownership',
    author: 'Crypto Gaming Enthusiast',
    date: 'May 12',
    content: 'How blockchain technology is transforming the gaming industry by allowing true ownership of in-game assets and new economic models.',
    likes: 13,
    comments: 21,
    collectCount: 131
  },
  {
    id: 13,
    image: 'https://picsum.photos/seed/post13/400/300',
    imageUrl: 'https://picsum.photos/seed/post13/400/300',
    title: 'The Role of Oracles in Bridging Web2 and Web3',
    author: 'Blockchain Infrastructure Specialist',
    date: 'May 15',
    content: 'Understanding the critical function of oracle networks in bringing real-world data onto the blockchain.',
    likes: 13,
    comments: 21,
    collectCount: 56
  },
  {
    id: 14,
    image: 'https://picsum.photos/seed/post14/400/300',
    imageUrl: 'https://picsum.photos/seed/post14/400/300',
    title: 'Decentralized Identity: Reclaiming Control of Personal Data',
    author: 'Privacy Advocate',
    date: 'May 17',
    content: 'Exploring the potential of blockchain-based identity solutions to enhance privacy and data sovereignty.',
    likes: 13,
    comments: 21,
    collectCount: 88
  },
  {
    id: 15,
    image: 'https://picsum.photos/seed/post15/400/300',
    imageUrl: 'https://picsum.photos/seed/post15/400/300',
    title: 'The Metaverse and Blockchain: Building Virtual Economies',
    author: 'Virtual World Designer',
    date: 'May 20',
    content: 'How blockchain technology is enabling the creation of robust economies within virtual worlds and metaverse platforms.',
    likes: 13,
    comments: 21,
    collectCount: 175
  },
  {
    id: 16,
    image: 'https://picsum.photos/seed/post16/400/300',
    imageUrl: 'https://picsum.photos/seed/post16/400/300',
    title: 'Tokenomics 101: Designing Sustainable Crypto Ecosystems',
    author: 'Tokenomics Researcher',
    date: 'May 22',
    content: 'A deep dive into the principles of token economics and how they can be applied to create thriving blockchain-based communities.',
    likes: 13,
    comments: 21,
    collectCount: 103
  },
  {
    id: 17,
    image: 'https://picsum.photos/seed/post17/400/300',
    imageUrl: 'https://picsum.photos/seed/post17/400/300',
    title: 'Cross-Chain Interoperability: Breaking Down Blockchain Silos',
    author: 'Blockchain Architect',
    date: 'May 25',
    content: 'Examining the latest developments in cross-chain communication and asset transfer protocols.',
    likes: 13,
    comments: 21,
    collectCount: 72
  },
  {
    id: 18,
    image: 'https://picsum.photos/seed/post18/400/300',
    imageUrl: 'https://picsum.photos/seed/post18/400/300',
    title: 'The Promise of Zero-Knowledge Proofs in Blockchain Privacy',
    author: 'Cryptography Expert',
    date: 'May 27',
    content: 'How zero-knowledge technology is enhancing privacy and scalability in blockchain networks.',
    likes: 13,
    comments: 21,
    collectCount: 119
  },
  {
    id: 19,
    image: 'https://picsum.photos/seed/post19/400/300',
    imageUrl: 'https://picsum.photos/seed/post19/400/300',
    title: 'Decentralized Science (DeSci): Revolutionizing Research Funding and Collaboration',
    author: 'Open Science Advocate',
    date: 'May 30',
    content: 'Exploring how blockchain can transform scientific research by enabling new models of funding, peer review, and data sharing.',
    likes: 13,
    comments: 21,
    collectCount: 84
  },
  {
    id: 20,
    image: 'https://picsum.photos/seed/post20/400/300',
    imageUrl: 'https://picsum.photos/seed/post20/400/300',
    title: 'The Future of Work: DAOs and the Gig Economy',
    author: 'Future of Work Researcher',
    date: 'June 1',
    content: 'Analyzing how Decentralized Autonomous Organizations are creating new paradigms for remote work and global collaboration.',
    likes: 13,
    comments: 21,
    collectCount: 147
  }
];